<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gym.proto

namespace GPBMetadata;

class Gym
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf010a0967796d2e70726f746f120b6c6967687477656967687422270a06506572736f6e120c0a046e616d65180120012809120f0a07616374696f6e7318022003280922220a055265706c79120c0a04636f6465180120012805120b0a036d736718022001280932400a0347796d12390a0c426f64794275696c64696e6712132e6c696768747765696768742e506572736f6e1a122e6c696768747765696768742e5265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

